<?php

/**
 * @file
 * Install, update and uninstall functions for the Logs HTTP module.
 */

/**
 * Implements hook_uninstall().
 */
function logs_rollbar_uninstall() {
  variable_del('logs_rollbar_enabled');
  variable_del('logs_rollbar_url');
  variable_del('logs_rollbar_rollbar_access_token');
  variable_del('logs_rollbar_rollbar_access_token_js');
  variable_del('logs_rollbar_severity_level');
  variable_del('logs_rollbar_uuid');
}
